# Generated by Django 5.2.6 on 2025-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='caption',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_url',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
