# Generated by Django 5.2.6 on 2025-12-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_portfolioitem_caption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioItem',
            new_name='PortfolioImage',
        ),
        migrations.RenameField(
            model_name='portfolioimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
