# Generated by Django 5.2.6 on 2025-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
