# Generated by Django 5.2.6 on 2025-09-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_photo_url_booking_status_booking_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('service', 'time')},
        ),
    ]
