# Generated by Django 5.2.6 on 2025-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_portfolioitem_portfolioimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
