# Generated by Django 5.2.6 on 2025-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_slot_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['time'], name='booking_slo_time_a16de2_idx'),
        ),
    ]
