# Generated by Django 5.2.6 on 2025-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_slot_booking_slo_time_a16de2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
