# Generated by Django 5.2.6 on 2025-12-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.client'),
        ),
    ]
