# Generated by Django 5.2.6 on 2025-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_master_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
