# Generated by Django 5.2.6 on 2025-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_master_avatar_url_master_bio_master_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_master_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
