# Generated by Django 5.2.6 on 2025-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_reminder_master_sent_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='master',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
