# Generated by Django 5.2.6 on 2025-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_mastereducation_masterspecialization_portfolioitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='минуты', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
