# Generated by Django 5.2.6 on 2025-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_service_description_service_duration_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', help_text='Телефон клиента', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик/Ввод данных'), ('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='draft', max_length=10),
        ),
    ]
